// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ThemeDoraemon.Migrations
{
    [DbContext(typeof(ThemeDoraemoncharacterContext))]
    partial class ThemeDoraemoncharacterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("ThemeDoraemon.ThemeCharacters.character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birth_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Character_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Favorite_Colour")
                        .HasColumnType("TEXT");

                    b.Property<string>("Favorite_Food")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("character");
                });
#pragma warning restore 612, 618
        }
    }
}
